n = str(input('Digite seu nome completo: ')).strip()
nmaiu = n.upper()
nminu = n.lower()
qnt = n.split()
qnt1 = ''.join(qnt)
print(f'Maiusculo: {nmaiu}')
print(f'Minusculo: {nminu}')
print(f'Total de letras {len(qnt1)}')
print(f'O primeiro nome tem: {len(qnt[0])} letras')