frase = str(input('Digite uma frase: ')).strip()
fl = frase.lower()
fp = fl.split()
fp1 = ''.join(fp)
qnta = fp1.count('a')
p1 = fp1.find('a')
pl = fp1.rfind('a')
print(f'A aparece: {qnta}x')
print(f'O primeiro "a" esta em {int(p1+1)}°')
print(f'O ultimo "a" esta em {int(pl+1)}°')